# Generated by Django 4.0 on 2021-12-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Models',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
